# Site settings
title: Oceans
email: nick@globalmechanic.com
description: "This is a description about the oceans project"
# baseurl: ""
url: ""
timezone: America/Vancouver
bodyclass: ""

# Build settings
markdown: kramdown
permalink: pretty
